export const VIDEOS_LOADING = 'VIDEOS_LOADING'
export const VIDEOS_LOAD_SUCCESS = 'VIDEOS_LOAD_SUCCESS'
export const VIDEOS_LOAD_FAILURE = 'VIDEOS_LOAD_FAILURE'

export const VIDEOS_ADD = 'VIDEOS_ADD'
export const VIDEOS_UPDATE = 'VIDEOS_UPDATE'
export const VIDEOS_REMOVE = 'VIDEOS_REMOVE'

